# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "16033dca3aae183dc7a59b7dae0586d1"
name = "BeforeBuy private feedback"
application_url = "https://beforebuy.cannyapps.com"
embedded = true
handle = "beforebuy-private-customer-feedback"

[webhooks]
api_version = "2024-07"

[access_scopes]
scopes = "read_customers,write_discounts,read_orders,write_products"

[auth]
redirect_urls = [
  "https://beforebuy.cannyapps.com/auth/callback",
  "https://beforebuy.cannyapps.com/auth/shopify/callback"
]
